package handler

import (
	"context"
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"

	"github.com/Tencent/WeKnora/internal/errors"
	"github.com/Tencent/WeKnora/internal/logger"
	"github.com/Tencent/WeKnora/internal/types"
	"github.com/Tencent/WeKnora/internal/types/interfaces"
	secutils "github.com/Tencent/WeKnora/internal/utils"
)

// CreateTenant godoc
// @Summary      创建空间
// @Description  创建新的空间。任意已登录用户均可调用以建立自己的新工作区，
// @Description  调用方会被自动设为该空间的 Owner。跨空间超管仍可像以前一样
// @Description  通过本接口创建任意空间。
// @Description  当 tenant.auto_create_api_key（或 WEKNORA_TENANT_AUTO_CREATE_API_KEY）
// @Description  开启时，会自动创建一个 full_access API Key，并在响应体的 data.api_key 字段返回其明文 token。
// @Tags         空间管理
// @Accept       json
// @Produce      json
// @Param        request  body      handler.createTenantRequest  true  "空间信息"
// @Success      201      {object}  map[string]interface{}  "创建的空间（可选含 api_key）"
// @Failure      400      {object}  errors.AppError         "请求参数错误"
// @Security     Bearer
// @Router       /tenants [post]
func (h *TenantHandler) CreateTenant(c *gin.Context) {
	ctx := c.Request.Context()

	logger.Info(ctx, "Start creating tenant")

	// Resolve the caller; required so we can bootstrap the Owner
	// membership and so we can branch on cross-tenant superuser status
	// for the legacy full-payload path.
	caller, err := h.userService.GetCurrentUser(ctx)
	if err != nil || caller == nil {
		logger.Error(ctx, "Failed to resolve current user from context", err)
		c.Error(errors.NewUnauthorizedError("authentication required"))
		return
	}
	apiKeyScope, hasAPIKeyScope := types.TenantAPIKeyScopeFromContext(ctx)
	platformCaller := hasAPIKeyScope && apiKeyScope.IsPlatform()
	catalogManager := caller.CanAccessAllTenants || platformCaller

	// Deployment-level policy: ordinary users may be restricted to joining
	// existing workspaces by invitation. This check is authoritative; the
	// frontend capability only improves UX and cannot bypass it. Cross-tenant
	// superusers retain the catalog-management create path.
	if !catalogManager &&
		!resolveTenantSelfServiceCreationEnabled(ctx, h.config, h.systemSettingSvc) {
		logger.Warnf(ctx, "Self-service tenant creation denied by policy for user %s", caller.ID)
		c.Error(errors.NewTenantCreationDisabledError())
		return
	}

	var tenantData types.Tenant

	if catalogManager {
		// Backward-compatible path for cross-tenant superusers: accept
		// the full Tenant payload (status, storage_quota, retriever
		// engines, configs...) so existing tooling keeps working.
		if err := c.ShouldBindJSON(&tenantData); err != nil {
			logger.Error(ctx, "Failed to parse request parameters", err)
			appErr := errors.NewValidationError("Invalid request parameters").WithDetails(err.Error())
			c.Error(appErr)
			return
		}
		// Reset client-supplied primary key so we don't accidentally
		// insert with a chosen ID that collides with a future
		// auto-increment value. Tenant IDs must always be DB-generated.
		tenantData.ID = 0
	} else {
		// Self-service path: a regular user can only set name and
		// description. Everything else is server-generated by
		// TenantService.CreateTenant (status="active", storage_quota
		// default, retriever engines from RETRIEVE_DRIVER). API keys are
		// created explicitly through the integration API-key list.
		var req createTenantRequest
		if err := c.ShouldBindJSON(&req); err != nil {
			logger.Error(ctx, "Failed to parse request parameters", err)
			appErr := errors.NewValidationError("Invalid request parameters").WithDetails(err.Error())
			c.Error(appErr)
			return
		}

		// Per-user quota: cap how many tenants a regular user can spin
		// up via self-service. Without this any authenticated client
		// can flood `tenants` (and saturate validateStorageBucketUniqueness
		// which scans the whole table). Superusers above are exempt
		// because they're already trusted to manage the catalog.
		if h.memberService != nil {
			memberships, listErr := h.memberService.ListByUser(ctx, caller.ID)
			if listErr != nil {
				logger.Errorf(ctx, "Failed to count owned tenants for user %s: %v", caller.ID, listErr)
				c.Error(errors.NewInternalServerError("Failed to validate workspace quota").WithDetails(listErr.Error()))
				return
			}
			ownedCount := 0
			for _, m := range memberships {
				if m != nil && m.Role == types.TenantRoleOwner {
					ownedCount++
				}
			}
			cap := h.resolveMaxOwnedTenantsPerUser(ctx)
			if cap > 0 && ownedCount >= cap {
				logger.Warnf(ctx,
					"User %s reached self-service tenant quota (%d/%d)",
					caller.ID, ownedCount, cap,
				)
				c.Error(errors.NewTooManyRequestsError(
					"reached self-service workspace quota; contact an administrator to raise the limit",
				))
				return
			}
		}

		tenantData = types.Tenant{
			Name:        strings.TrimSpace(req.Name),
			Description: strings.TrimSpace(req.Description),
		}
	}

	// Apply the system-setting-driven default storage quota when the
	// caller didn't specify one (always true for self-serve; sometimes
	// true for the superuser branch when the JSON omits storage_quota).
	// We resolve at create time on purpose — the on-disk row should
	// carry an explicit value, so changing the setting later doesn't
	// silently shrink/grow established tenants. Negative values are
	// treated as "use default" so a misconfigured setting can't yield
	// a negative quota that the storage-used checks would interpret as
	// "unlimited" (StorageQuota <= 0 disables enforcement in
	// knowledge_create.go).
	if tenantData.StorageQuota <= 0 {
		gb := h.systemSettingSvc.GetInt(
			ctx,
			"tenant.default_storage_quota_gb",
			"WEKNORA_TENANT_DEFAULT_STORAGE_QUOTA_GB",
			10,
		)
		if gb <= 0 {
			gb = 10
		}
		tenantData.StorageQuota = gb * 1024 * 1024 * 1024
	}

	logger.Infof(ctx, "Creating tenant, name: %s", secutils.SanitizeForLog(tenantData.Name))

	createdTenant, err := h.service.CreateTenant(ctx, &tenantData)
	if err != nil {
		// Check if this is an application-specific error
		if appErr, ok := errors.IsAppError(err); ok {
			logger.Error(ctx, "Failed to create workspace: application error", appErr)
			c.Error(appErr)
		} else {
			logger.ErrorWithFields(ctx, err, nil)
			c.Error(errors.NewInternalServerError("Failed to create workspace").WithDetails(err.Error()))
		}
		return
	}

	// Bootstrap an Owner membership so the caller immediately has full
	// control over the tenant they just created. We MUST roll the tenant
	// back if this fails: without a membership row the new tenant is
	// unreachable (middleware/auth.go's orphan-recovery only fires for a
	// user's home tenant, never for a freshly-created side workspace),
	// yet still occupies storage_bucket / name uniqueness slots.
	// Idempotent: EnsureOwner is a no-op when the row already exists,
	// so cross-tenant superusers create-and-own through the same path.
	if h.memberService != nil && !platformCaller {
		if _, err := h.memberService.EnsureOwner(ctx, caller.ID, createdTenant.ID); err != nil {
			logger.Errorf(ctx,
				"Failed to bootstrap owner membership for user %s tenant %d: %v — rolling back tenant",
				caller.ID, createdTenant.ID, err)
			if delErr := h.service.DeleteTenant(ctx, createdTenant.ID); delErr != nil {
				logger.Errorf(ctx,
					"Rollback DeleteTenant failed for orphan tenant %d: %v",
					createdTenant.ID, delErr,
				)
			}
			c.Error(errors.NewInternalServerError("Failed to finalise workspace ownership").WithDetails(err.Error()))
			return
		}

		// Quota TOCTOU guard. The earlier ownedCount check is racy:
		// N concurrent CreateTenant calls all read ownedCount < cap,
		// all proceed, all insert. Re-count AFTER the Owner membership
		// is committed; if we landed over the cap, roll back this
		// tenant + its membership so the bound holds in steady state.
		// We only do this for non-superusers (the only path that has
		// a cap) — superusers are exempt above.
		if !caller.CanAccessAllTenants {
			memberships, listErr := h.memberService.ListByUser(ctx, caller.ID)
			if listErr != nil {
				logger.Errorf(ctx, "Post-create quota recount failed for user %s tenant %d: %v",
					caller.ID, createdTenant.ID, listErr)
			} else {
				ownedNow := 0
				for _, m := range memberships {
					if m != nil && m.Role == types.TenantRoleOwner {
						ownedNow++
					}
				}
				cap := h.resolveMaxOwnedTenantsPerUser(ctx)
				if cap > 0 && ownedNow > cap {
					logger.Warnf(ctx,
						"User %s exceeded tenant quota after concurrent create (%d/%d), rolling back tenant %d",
						caller.ID, ownedNow, cap, createdTenant.ID,
					)
					if rmErr := h.memberService.RemoveMember(ctx, caller.ID, createdTenant.ID); rmErr != nil {
						logger.Errorf(ctx,
							"Rollback RemoveMember failed for user %s tenant %d: %v",
							caller.ID, createdTenant.ID, rmErr,
						)
					}
					if delErr := h.service.DeleteTenant(ctx, createdTenant.ID); delErr != nil {
						logger.Errorf(ctx,
							"Rollback DeleteTenant failed for over-quota tenant %d: %v",
							createdTenant.ID, delErr,
						)
					}
					c.Error(errors.NewTooManyRequestsError(
						"reached self-service workspace quota; contact an administrator to raise the limit",
					))
					return
				}
			}
		}
	}

	// When a tenantless user creates their first workspace, make it their
	// default login tenant. Roll the just-created resources back if this
	// finalisation fails so the user is not left with an unreachable tenant.
	if caller.TenantID == 0 && !platformCaller {
		caller.TenantID = createdTenant.ID
		if err := h.userService.UpdateUser(ctx, caller); err != nil {
			logger.Errorf(ctx, "Failed to set first tenant %d as default for user %s: %v",
				createdTenant.ID, caller.ID, err)
			if h.memberService != nil {
				_ = h.memberService.RemoveMember(ctx, caller.ID, createdTenant.ID)
			}
			_ = h.service.DeleteTenant(ctx, createdTenant.ID)
			c.Error(errors.NewInternalServerError("Failed to finalise default workspace").WithDetails(err.Error()))
			return
		}
	}

	logger.Infof(
		ctx,
		"Tenant created successfully, ID: %d, name: %s",
		createdTenant.ID,
		secutils.SanitizeForLog(createdTenant.Name),
	)

	// data carries the created tenant. When the legacy auto-create-key
	// behaviour is enabled we embed the plaintext token as data.api_key so
	// the response shape mirrors the pre-break-change behaviour integrations
	// relied on.
	var data any = createdTenant

	// Optional legacy compatibility: mint a full-access API key on tenant
	// creation and return its plaintext token, gated by the
	// tenant.auto_create_api_key setting (env WEKNORA_TENANT_AUTO_CREATE_API_KEY).
	// Default off — modern deployments create keys explicitly via
	// tenant_api_keys. Failing to create the convenience key must NOT fail
	// the whole tenant creation (the tenant is fully usable without a key);
	// we log a warning and return the tenant as usual.
	// A platform key with system_tenants_manage may create workspaces, but it
	// must not bootstrap a full-access workspace key and escalate beyond its
	// own explicit capabilities.
	if !platformCaller && h.autoCreateTenantAPIKey(ctx) && h.apiKeyService != nil {
		result, keyErr := h.apiKeyService.CreateAPIKey(ctx, interfaces.TenantAPIKeyCreateRequest{
			TenantID:   createdTenant.ID,
			ScopeType:  types.APIKeyScopeTenant,
			Name:       "default",
			FullAccess: true,
		})
		if keyErr != nil {
			logger.Errorf(ctx,
				"Auto-create default API key failed for tenant %d: %v — returning tenant without key",
				createdTenant.ID, keyErr)
		} else if merged, mErr := tenantWithAPIKey(createdTenant, result.Token); mErr != nil {
			// Round-trip failure is unexpected; degrade gracefully by
			// returning the tenant without embedding the key rather than
			// failing the whole request.
			logger.Errorf(ctx, "Failed to embed api_key into tenant response for tenant %d: %v",
				createdTenant.ID, mErr)
		} else {
			data = merged
		}
	}

	c.JSON(http.StatusCreated, gin.H{
		"success": true,
		"data":    data,
	})
}

// tenantWithAPIKey returns the tenant serialized as a map with an extra
// api_key field, so the create response can embed the plaintext token inside
// data (mirroring the pre-break-change shape) without adding a persisted
// api_key column back onto types.Tenant.
func tenantWithAPIKey(tenant *types.Tenant, token string) (map[string]any, error) {
	raw, err := json.Marshal(tenant)
	if err != nil {
		return nil, err
	}
	m := map[string]any{}
	if err := json.Unmarshal(raw, &m); err != nil {
		return nil, err
	}
	m["api_key"] = token
	return m, nil
}

// autoCreateTenantAPIKey resolves whether tenant creation should also mint a
// full-access API key (legacy compatibility). 3-tier resolver:
// system_settings DB row > WEKNORA_TENANT_AUTO_CREATE_API_KEY env > false.
func (h *TenantHandler) autoCreateTenantAPIKey(ctx context.Context) bool {
	if h.systemSettingSvc == nil {
		return false
	}
	return h.systemSettingSvc.GetBool(
		ctx,
		"tenant.auto_create_api_key",
		"WEKNORA_TENANT_AUTO_CREATE_API_KEY",
		false,
	)
}
